import Head from "next/head"
import Header from "../../include/header"
import Menu from "../../include/menu"
import Footer from "../../include/footer"
import Principal from "../../supertags/principal"
import Titulo from "../../supertags/titulo"
import ScriptAnalytics from "../../scripts/script-analytics"

function psicanalise_52(){
    return(
        <>
        <Head>
            <title>A Busca pelo Prazer e a Culpa Reparadora</title>
            <meta name="keywords" content="arrependimento sentimento de culpa"/>
            <meta name="description" content="...Na abordagem da psicanálise esse instrumento de controle e autocensura da qual muitos buscam escapar é chamado de SUPEREGO, enquanto que o mecanismo psíquico que  impulsiona as pessoas à busca pelo prazer e pela satisfação imediata dos seus instintos recebe o nome de ID..."/>
        </Head>
        <ScriptAnalytics/>
        <Header/>
        <Menu/>
        <Principal>
            <Titulo>A BUSCA PELO PRAZER E A CULPA REPARADORA</Titulo>
            <p>Desde o princípio da sua história a humanidade parece viver a ambiguidade entre a busca pela satisfação dos seus desejos e a prática de rituais de penitência que possam lhes oferecer algum conforto espiritual, talvez  porque esses rituais possuem a suposta prerrogativa de reparar o sentimento de culpa provocado por algum exagero cometido. Em sua busca pela satisfação é comum as sociedades promoverem festividades coletivas, com o intuito de alcançarem o nível de prazer e êxtase que individualmente dificilmente conseguiria obter. A oportunidade de espelhamento no outro que as festividades permitem, serve para inibir o mecanismo de censura presente nas pessoas, fazendo com que o mecanismo do prazer e da ausência de controle seja liberado, concedendo aos indivíduos um alto nível de permissividade, marcada pela ausência de equilíbrio e moderação. Na Antiguidade Romana por exemplo, eram famosas as festividades profanas em homenagem ao deus do vinho e da fertilidade, Baco. Nessas festas as pessoas se entregavam às orgias (bacanais) regadas a muito vinho e comida, festividades estas que se estendiam por dias a fio. Nos dias de hoje a principal festividade coletiva é o carnaval, uma festa pagã que no início dos tempos também era celebrado para cultuar as divindades da fertilidade. Durante essas festividades as pessoas utilizavam máscaras e disfarces para poderem liberar toda sua fantasia e desejos sem que fossem reconhecidas. É como se as máscaras e fantasias estivessem a dizer: “tudo é permitido, o carnaval é de todos e para todos.” Além disso, as festividades carnavalescas promovem a ilusão de igualdade entre as pessoas, visto que na formação das alegorias e blocos há uma mistura de classe social, situação em que famosos e anônimos partilham o mesmo espaço, no qual se permite, inclusive, que uma pessoa do povo assuma o posto de rainha ou rei por um certo período, produzindo assim a ideia de uma quebra na ordem social, por permitir a inversão de papeis e valores. Essa fuga da realidade, mesmo que notoriamente fantasiosa e passageira, é capaz de promover conforto àquele que penosamente trabalha o ano todo para minimamente dar conta das suas necessidades básicas de sobrevivência.</p>
            <p>Na abordagem da psicanálise esse instrumento de controle e autocensura da qual muitos buscam escapar é chamado de SUPEREGO, enquanto que o mecanismo psíquico que  impulsiona as pessoas à busca pelo prazer e pela satisfação imediata dos seus instintos recebe o nome de ID. Enquanto o primeiro é fruto da  educação para a vida em sociedade, com toda sua carga de cobranças, proibições, culpa e punições, o segundo acompanha a pessoa desde o seu nascimento, sendo responsável por impulsioná-la a buscar a satisfação imediata das suas necessidades e pela busca de compensação prazerosa  diante daquilo que está fazendo. Nessa luta constante entre desejo e culpa é comum o desenvolvimento de uma neurose obsessiva que clama por um alívio que em muitos casos é alcançado por atos supostamente reparadores como os rituais de penitência.</p>
            <p>Como diria o poeta Vinícius de Morais: “a gente trabalha o ano inteiro, por um momento de sonho, pra fazer fantasia de rei ou pirata ou jardineira, pra tudo acabar na quarta-feira”. O problema para muitos reside exatamente na chegada da  quarta-feira, quando o indivíduo que, guiado pelo seu princípio de prazer e permissividade (ID), volta para a sua realidade, a sua casa, e se depara com aquele seu outro lado, como o pai autoritário que lhe espera no portão para cobrar explicações sobre tudo aquilo que ele andou fazendo e que não contava com sua aprovação. Mesmo sem dizer nada, sua simples presença faz com que o sentimento de culpa de manifeste, normalmente de forma inconscientemente. Nos indivíduos em que esse mecanismo de cobrança tem predominância, a presença da culpa e a necessidade de redenção se torna muito forte, tornando os períodos de recolhimento e penitência  fatores altamente necessários para que eles consigam promover um relativo equilíbrio entre os aspectos  sagrados e profanos que constituem a vida psíquica de cada pessoa. Essa relação equilibrada é alcançada na medida em que a pessoa consiga estabelecer a coexistência harmoniosa entre a busca pela satisfação e ação consciente de permissividade, situação em que ela tranquilamente se permite desfrutar daquilo que os momentos festivos possam lhe propiciar, sem precisar recorrer a subterfúgios que a protejam do seu próprio julgamento e do julgamento de outrem, visto que haverá o entendimento de que a alegria e o prazer podem muito bem fazer parte da vida de todos. Se assim for, os momentos de contemplação e penitência servirão como caminhos para acrescentar mais espiritualidade e vida ao nosso ser, deixando assim de ter aquela conotação de mero reparador de um vazio que as ações instintivas podem nos provocar. Que possamos desfrutar daquilo que a vida tem a nos oferecer sem ser corroído pela culpa ou remorso, grandes vilões do nosso bem-estar e da felicidade.</p>
        </Principal>
        <Footer/>
        </>
    )
}

export default psicanalise_52;