import Header from "../../include/header";
import Principal from "../../supertags/principal";
import Menu from "../../include/menu";
import Footer from "../../include/footer";
import Titulo from "../../supertags/titulo";
import HeadConfig from "../../include/head";

function Curso_03 (){
    return (
        <>
        <HeadConfig/>
        <Header/>
        <Menu/>
        <Principal>
            <Titulo>GRUPO DE PAIS: DESENVOLVENDO VALORES NA EDUCAÇÃO</Titulo>
            <blockquote>&ldquo;A educação deve preparar a criança para uma vida adulta ativa numa sociedade livre e promover o respeito pelos pais, pela própria identidade cultural, pela língua e pelos valores e por outras culturas e outros valores.&rdquo;</blockquote>
                <h3>JUSTIFICATIVA</h3>
                <p>Pais, educadores e um número cada vez maior de pessoas têm demonstrado muita preocupação com a violência, com os problemas sociais crescentes e com a falta de respeito pelo outro e pelo mundo ao redor, sendo  afetados por toda esta gama de problemas. Por outro lado, a maioria dos pais demonstra uma séria dificuldade de comunicação e de relacionamento com os seus filhos, de forma que não sabem o que fazer quando estes enfrentam certas questões que comprometem a sua existência. Ao mesmo tempo, temem a influência das outras pessoas e gostariam de atuar de maneira mais direta para dar aos filhos um rumo certo,  sobretudo no período em que sua personalidade se encontra em franca transformação.</p>
                <p>O presente projeto pretende contribuir para que os pais se sintam melhores instrumentalizados para enfrentar essas angústias, devendo funcionar de forma que eles possam partilhar sua sabedoria e seus desafios, explorando valores e aumentando o conhecimento acerca das suas próprias habilidades e as dos seus filhos.</p>
                <h3>OBJETIVOS</h3>
                <p>O objetivo principal dos encontros será o de contribuir para que os pais adquiram condições de refletir sobre os valores que gostariam que os filhos praticassem, através da aplicação de métodos que os levam a incorporar em sua própria prática cotidiana os valores que eles ajudarão seus filhos a desenvolver. Os encontros serão planejados visando que os pais:</p>
                <ul className="lista-conteudo">
                    <li>avaliem que valores consideram mais importantes;</li>
                    <li>certifiquem-se de quais valores desejam transmitir aos filhos;</li>
                    <li>tomem consciência  de como as crianças aprendem os valores;</li>
                    <li>desenvolvam a compreensão e as habilidades necessárias à extração dos valores de seus filhos;</li>
                    <li>passem a olhar para a educação como uma filosofia de vida e, por meio dela, facilitar o crescimento geral, o desenvolvimento e as escolhas dos filhos, de modo a integrá-lo na sociedade com respeito, confiança e propósitos firmes.</li>
                </ul>
                <h3>REFERENCIAL TEÓRICO</h3>
                <p>Para a elaboração e execução do projeto nos ampararemos em três princípios teóricos básicos que são:</p>
                <p>a maiêutica socrática, uma vez que o nosso trabalho, a exemplo da prática desenvolvida por Sócrates, não pretende oferecer normas e procedimentos valorativos previamente definidos e criados pelos adultos, mas oferecer condições a que cada um enquanto indivíduo possa elaborar as suas próprias normas  e colocar-se, a partir daí, à disposição do grupo. Seguindo este princípio acreditamos estar contribuindo para a geração de pessoas pensantes, criativas e, sobretudo, conscientes de que a convivência saudável na sociedade passa necessariamente por tomadas de atitudes voluntárias, livres e, nem por isso, irresponsáveis e inconseqüentes.</p>
                <p>Para tanto partimos do pressuposto de que o indivíduo é capaz de se auto-regulamentar de forma a conduzir sua existência de maneira fluida, feliz e, ao mesmo tempo, respeitar o direito alheio, cumprir os deveres que lhes forem competentes, sem que haja a necessidade de qualquer mecanismo de coerção. Oferecer condições a que ele consiga atingir tal nível de autonomia é o horizonte por nós vislumbrado ao nos recorrermos à maiêutica socrática como um dos suportes teóricos para o nosso trabalho.</p>
                <p>1	Outro recurso do qual lançaremos mão é a técnica criada<b> por Mathew Lipman, conhecida ”como educação para o pensar – filosofia para criança.” </b>Essa concepção nos parece importante por defender uma prática dialógica e que tem em vista a formação da pessoa em todas as suas dimensões. Para tanto ela parte da negação das pseudoverdades que normalmente são apenas aprendidas (não apreendidas) e assumidas pelos alunos, as quais por serem &ldquo;dadas&rdquo; de uma maneira aproblemática, em nada contribuem para a real elaboração de concepções novas, não permitindo portanto, a reelaboração das verdades já cristalizadas.</p>
                
                <p>É partindo dos desencontros surgidos no cotidiano familiar que esperamos encontrar abertura para discutir os problemas de relacionamento entre pais e filhos, buscando formas saudáveis de superá-los de maneira justa e, sobretudo, harmoniosa. Encarados desta forma, aquilo que poderia ser visto como problema, na verdade é um valioso instrumento do qual podemos lançar mão, subsidiário que é dos elementos concretos necessários à busca de soluções para a onda de violência que sofremos e que, por não conhecermos mecanismos de absorção eficazes, devolvemo-la sob as mais diversas formas às pessoas do nosso círculo de convivência.</p>
                <p>Paulo Freire falava da utopia enquanto ato de denunciar a sociedade naquilo que ela tem de injusta e de desumanizadora e enquanto ato de anunciar a nova sociedade. Denunciar e anunciar são utopias. Precisamos formar seres que sonhem com uma sociedade humanizadora, justa, verdadeira, alegre, com participação de todos nessa construção.</p>
                <p>O terceiro referencial será o projeto desenvolvido pela Universidade Mundial Brahma Kumaris, intitulado Vivendo Valores na Educação o qual fora concebido pautando-se pelos seguintes princípios: &ldquo;os valores são o tesouro da vida, tornando os seres humanos ricos e prósperos em todos os aspectos da sua vida. E que uma vida preenchida com valores é uma vida pautada no auto-respeito e dignidade. Os valores promovem independência e liberdade, expandem a capacidade de sermos auto-suficientes e nos liberam de influências externas e, à medida que os desenvolvemos dentro do eu, partilhamos a fragrância destes valores com o mundo ao nosso redor e, deste modo, avançamos em direção a um mundo melhor&rdquo;.</p>
                <p>Esse projeto foi desenvolvido em razão da comemoração do cinqüentenário da ONU, em parceria com o UNICEF, tendo sido aplicado em mais de sessenta países, propondo um programa de atividades baseado em princípios éticos e espirituais, para que possam ser vivenciados na instituição familiar, tornando-a um elemento indispensável na reconstrução de uma sociedade melhor. Dentro deste processo de crescimento ativo, o indivíduo pode revelar uma capacidade de estender-se para além dos limites da realidade atual e reconhecer seu potencial completo, não apenas em relação ao eu, mas também em relação ao mundo de uma forma mais ampla. Desta forma, acreditamos que ao lançarmos mão desta proposta estaremos oferecendo aos pais e, extensivamente aos seus filhos, de uma maneira bastante eficaz, os instrumentais necessários a que ele se volte para dentro de si, a fim de analisar suas atitudes frente a si mesmo e aos outros, com o intuito de tornar-se cada vez melhor dentro daquilo que é inerente aos verdadeiros valores humanos. </p>
                <h3>CONTEÚDO:</h3>
                <p>Visando primeiramente o desenvolvimento integral da criança, gerando assim o seu bem-estar interno, consideramos que o primeiro passo é estimulá-la a ir em busca do entendimento do seu ser  e de suas qualidades que acreditamos inatas em cada indivíduo, como o sentimento de  paz, felicidade, verdade, pureza, amor, equilíbrio. É necessário que a criança compreenda que aquilo que tão ansiosamente busca no mundo externo, encontra-se escondido em cada um. Nossa tarefa tanto como pais quanto como educadores é a de contribuir para o reflorescimento deste potencial existente em cada criança.</p>
                <p>Assim propomos que os encontros sejam permeados por discussões acerca das preocupações comumente apresentadas pelos pais, cujo objetivo será o de desenvolver habilidades necessárias ao bom desempenho da tarefa de educar para os valores, a saber:</p>
                <h4>PREOCUPAÇÃO DOS PAIS: &ldquo;não tenho tempo.&rdquo;</h4>
                <p><b>HABILIDADE: a importância da brincadeira e do &ldquo;tempo para nós&rdquo;: </b>Ter tempo para brincar diariamente com  seus filhos é muito importante. É um momento precioso em que os relacionamentos são avaliados e o amor aumenta. As crianças que têm &ldquo;tempo para nós&rdquo; recebem toda a atenção e um contato que lhes diz que são valorizadas e preciosas.</p>
                <h4>PREOCUPAÇÃO DOS PAIS: &ldquo;ele se comporta mal para chamar a minha atenção;&rdquo; &ldquo;ela não gosta de receber elogios.&rdquo;</h4>
                <p>HABILIDADE: construindo positivamente o comportamento através do elogio: as crianças precisam da atenção dos pais. Geralmente elas se dão melhor nas áreas em que recebem elogios e afetos. Todos gostam de receber atenção, amor e respeito. As crianças podem fazer as coisas esperando essas respostas positivas se elas estiverem disponíveis. Gasta-se menos energia emocional ao prestar atenção positiva e reforçar um comportamento positivo do que se ater a fatos e/ou comportamentos negativos.</p>
                <h4>3	PREOCUPAÇÃO DOS PAIS: &ldquo;ele só querem ver televisão;&rdquo; &ldquo;adoram filmes violentos.&rdquo;</h4>
                <p>HABILIDADE: o equilíbrio entre a disciplina e o amor: os pais geralmente reconhecem a importância de uma dieta saudável. Querem que seus filhos façam refeições nutritivas e  desenvolvam  bons hábitos alimentares. Eles escolhem a comida que a família deve comer. O alimento para a mente tem a mesma importância. A dieta oferecida pela televisão afeta a mente e o comportamento das crianças. Não só ela tem o desenvolvimento físico comprometido como também a linguagem expressiva, a criatividade e as habilidades sociais.</p>
                <p>Ser um pai equilibrado entre a disciplina e o amor é saber que as crianças precisam ter regras a aprender sobre aquilo que lhes faz bem. Ter o controle dos programas de televisão aos quais as crianças são expostas, assim como dos ambientes que elas freqüentam é uma atitude responsável e amorosa.</p>
                <h4>PREOCUPAÇÃO DOS PAIS: &ldquo;ele fica tão bravo com os professores...&rdquo;</h4>
                <p>HABILIDADE: escuta ativa: uma das melhores ferramentas para ouvir é a chamada escuta ativa. Escutar ativamente é absorver e refletir sobre o conteúdo e as emoções da outra pessoa. A habilidade de ouvir com paciência e amor é um presente precioso. Refletir os sentimentos das crianças faz com que elas os aceitem e se tornem “proprietárias” das próprias emoções.</p>
                <h4>PREOCUPAÇÃO DOS PAIS: &ldquo;as coisas mudam muito depressa e as crianças ficam inseguras.&rdquo;</h4>
                <p>HABILIDADE: criação de rituais para manter a ordem emocional: quanto às mudanças, certas crianças ficam retraídas e deprimidas, outras lamentam ou tornam-se agressivas. A criação de certos rituais pode contribuir para que a ordem emocional seja restabelecida, uma vez que eles dão às crianças a idéia de constância  e consistência, fazendo com que elas possam sentir-se mais seguras e tranqüilas.</p>
                <h4>6	PREOCUPAÇÃO DOS PAIS: &ldquo;eu digo &lsquo;não&rsquo; e ele fica em cima de mim até eu ceder.&rdquo;</h4>
                <p>HABILIDADE: pensar antes de dizer &ldquo;não!&rdquo;: às vezes dizemos &ldquo;não&rdquo; por impulso. Estamos tão ocupados que não queremos ser incomodados. Mas os pais tendem a se sentir culpados quando dizem não sendo que a resposta poderia ter sido um sim. Por outro lado, as crianças escutam quando os pais dizem uma coisa, sustentam e fazem o que dizem. Portanto, é interessante que os pais aprendam a comprometerem-se de maneira coerente e aprendam também a cumprir as promessas feitas.</p>
                <h4>7	PREOCUPAÇÃO DOS PAIS: &ldquo;quero que meu filho seja pacífico, mas eu mesmo não sou.&rdquo; &ldquo;Não tenho energia sobrando.&rdquo;</h4>
                <p>HABILIDADE: tempo para ser: para transmitir bons valores, precisamos tê-los e aplicá-los, o que às vezes é difícil. A maioria de nós deseja ser pacífico, amável e feliz. No entanto, às vezes estamos de mau humor, num dia ruim em que as coisas não estão dando certo. Ser pai é transmitir aos seus filhos um modelo sustentável de &ldquo;ser&rdquo;.</p>
                <h4>8	PREOCUPAÇÃO DOS PAIS: &ldquo;eles não fazem nada do que eu peço.&rdquo;</h4>
                <p>HABILIDADE: manter-se estável e amoroso, desenvolvendo sempre a comunicação equilibrada: a irritação imprime um tom raivoso ao relacionamento. É  mais fácil nos mantermos estáveis e amorosos quando reconhecemos que é apenas uma fase pela qual a criança está passando e que pode ser bem trabalhada se estivermos emocionalmente equilibrados e a respeitarmos como ser humano. É importante que nós adultos tenhamos consciência de que temos muito a aprender com as crianças e que encaremos essa situação como uma oportunidade de crescimento mútuo.</p>
                <h4>PREOCUPAÇÃO DOS PAIS: &ldquo;eles vivem brigando. Isso prejudica até as atividades de lazer.&rdquo;</h4>
                <p>HABILIDADE: tempo para pensar e comunicar-se (etapas para solução de conflitos): dar um tempo é um método usado em crianças que se comportam de maneira inadequada. Elas são convidadas a sair da sala e ficar sozinhas durante um tempo que não deve ser longo. Não se trata de uma punição, mas de uma atitude em que os pais suspendem temporariamente a atenção que costumam dar a elas. A principal razão para implantar o &ldquo;tempo&rdquo; é que, quando feito de maneira apropriada, as medidas punitivas podem ser dispensadas.</p>
                <p>Acreditamos que essa proposta, se bem assimilada, ajudará a satisfazer nas crianças as suas necessidades interiores, o que certamente resultará em significados positivos no nosso meio social, partindo da conscientização da verdadeira identidade do indivíduo, posicionando-se como elemento único, fugindo da massificação que os mecanismos sociais tentam lhe imputar. Acreditamos ainda que a conquista da auto-estima é o resultado natural deste laboratório cotidiano. Assim, os desvios de identidade que se encontram arraigados em boa parte das pessoas podem encontrar seu caminho de retorno dando a elas um significado maior para a sua existência. Para tanto, pretendemos abordar em nossos encontros os seguintes valores:</p>
                <ul className="lista-conteudo">
                    <li>PAZ:  construir a concepção de que a paz é um valor a ser concebido no interior de cada um de nós, sendo estado de consciência vivo e construtivo, ressaltando a diferença entre ser pacífico e ser passivo;</li>
                    <li>RESPEITO: gerar a noção de respeito por si, pelo outro, pelas regras de convivência social, levando-os a compreender a importância da aplicação desse valor para a salubridade de nossas relações;</li>
                    <li>AMOR:  compreender as diversas concepções de amor  e suas implicações para o relacionamento saudável e construtivo, criando capacidade de reconhecer e questionar as diversas deturpações que freqüentemente lhe atribuímos;</li>
                    <li>FELICIDADE:  refletir sobre os modelos de felicidade perseguidos pela maioria das pessoas, procurando verificar se essa busca realmente deve acontecer no mundo exterior, uma vez que o trabalho parte do princípio de que a verdadeira felicidade encontra-se no interior de cada indivíduo, bastando apenas que o mesmo chegue a tal constatação e direcione seus atos para deixar fluir tal valor, o qual acreditamos repercutirá em sua qualidade de vida, através de atitudes construtivas e saudáveis;</li>
                    <li>HONESTIDADE: entender que honestidade significa a não existência de contradições ou discrepâncias em pensamentos, palavras ou ações, compreendendo ainda que ser honesto com o nosso eu real e com o propósito de uma tarefa, conquista confiança e inspira fé nos outros e que honestidade é jamais usar erroneamente aquilo que é dado em confiança;</li>
                    <li>HUMILDADE: compreender que uma pessoa que incorpora esse valor se esforçará por escutar e aceitar os outros, compreendendo que quanto maior for a aceitação dos outros, mais a pessoa será mantida em alta estima e mais ela será escutada;</li>
                    <li>RESPONSABILIDADE: entender responsabilidade não como uma carga, mas como uma expressão de interesse. Como a habilidade de tomar consciência de que a atitude responsável individual é fundamental para que a família ou outro grupo social como um todo alcance seus intentos;</li>
                    <li>SIMPLICIDADE: compreender que o caminho para uma vida saudável e feliz pode estar na valorização das coisas simples da vida, em contraste com o apelo da sociedade de consumo que nos bombardeia com necessidades cada vez mais complexas e difíceis de se satisfazer, as quais contribuem sobremaneira para a noção geral de insatisfação que nos cerca;</li>
                    <li>TOLERÂNCIA: incentivar a reflexão acerca da convivência com as diferenças e suas implicações, reconhecendo tais diferenças como elementos de crescimento, na certeza de pertencermos todos ao mesmo grupo, a saber a comunidade humana;</li>
                    <li>COOPERAÇÃO: desenvolver nos filhos o prazer do trabalho em familia e a importância da ação individual na contribuição com o todo, entendendo o ato de cooperar como uma prática fundamental para o desenvolvimento de relacionamentos harmoniosos. Esperamos ainda, que ele entenda que cooperar significa contribuir com idéias e ações para servir ao grupo familiar e não usar o grupo para servir às suas próprias idéias e interesses;</li>
                    <li>LIBERDADE: refletir sobre as diversas concepções de liberdade preconizada pela nossa sociedade, procurando distinguir entre aquilo que de fato é e o que falsamente se prega como tal. Desta forma pretendemos que ao fazer tal análise o indivíduo adquira condições de discernimento afim de que não se torne escravo daquilo que ele julga ser a expressão máxima da sua liberdade, entendendo que ela, na sua concepção extrema, funciona apenas quando os direitos são equilibrados com responsabilidade e opção é equilibrada com consciência.</li>
                    <li>UNIÂO: construir o sentimento de pertencer ao grupo, qualquer que seja ele, sentindo-se co-responsável pela harmonia e conquistas dos objetivos comuns, compreendendo que na união é necessário compartilhar, concordar e realizar uma mesma tarefa para a felicidade de todos;</li>
                </ul>
                <h4>METODOLOGIA:</h4>
                <p>Os nossos encontros ocorrerão em forma de workhshops, durante os quais procuraremos envolver os pais através de atividades lúdicas e agradáveis, sem no entanto, perder a seriedade necessária ao sucesso que almejamos. O processo deverá ocorrer de acordo com as seguintes etapas:</p>
                <ol className="lista-conteudo">
                    <li>descrição do conteúdo e das atividades com introdução do processo para a exploração de cada valor. Nesta etapa os pais refletem sobre seus próprios valores e como vivenciam e ensinam esses valores;</li>
                    <li>desenvolvimento de atividades relativas aos valores que os pais podem explorar em casa junto aos seus filhos. O intuito é que, ao fazerem as brincadeiras que seus filhos fazem, os pais aprendam métodos adicionais para desenvolver a dimensão emocional e melhorar as relações sociais baseadas em valores;</li>
                    <li>discussão acerca das preocupações comuns dos pais, com reflexão sobre as condições necessárias para enfrentar esses desafios, além de se levantar propostas de ações efetivas em direção à solução dos eventuais problemas presentes.</li>
                </ol>
                <h3>PÚBLICO:</h3>
                <p>Pais, educadores e estudantes de Pedagogia.</p>
                <h3>CRONOGRAMA:</h3>
                <p>Prevemos a realização de vinte encontros, com duração de duas horas cada, os quais deverão ocorrer uma vez por semana. Destas duas horas, noventa minutos serão utilizados para o desenvolvimento das atividades previstas e os outros trinta serão reservados para conversas particulares com alguns pais que demonstrarem alguma necessidade especial de acompanhamento. Ressaltamos que se houver necessidade, os encontros poderão se estender por mais algum período até que as demandas apresentadas pelos pais possam ser atendidas.</p>
        </Principal>
        </>
    )
}

export default Curso_03